
default:

clean:
	rm -f mint-temporarily.h

mint-temporarily.h: src/add-mint-temporarily.h src/and-mint-temporarily.h src/copy-mint-temporarily.h src/div-mint-temporarily.h src/floor-mint-temporarily.h src/lshift-mint-temporarily.h src/make-mint-temporarily.h src/mod-mint-temporarily.h src/mul-mint-temporarily.h src/not-mint-temporarily.h src/or-mint-temporarily.h src/rshift-mint-temporarily.h src/sub-mint-temporarily.h src/xor-mint-temporarily.h src/minus-mint-temporarily.h
	cat src/add-mint-temporarily.h src/and-mint-temporarily.h src/copy-mint-temporarily.h src/div-mint-temporarily.h src/floor-mint-temporarily.h src/lshift-mint-temporarily.h src/make-mint-temporarily.h src/mod-mint-temporarily.h src/mul-mint-temporarily.h src/not-mint-temporarily.h src/or-mint-temporarily.h src/rshift-mint-temporarily.h src/sub-mint-temporarily.h src/xor-mint-temporarily.h src/minus-mint-temporarily.h > mint-temporarily.h
